spring.datasource.url=jdbc:h2:mem:repetition7;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.dev.admin.username=admin
app.dev.admin.password=admin123
app.dev.admin.enabled=true
app.jwt.issuer=repetition7-dev
app.jwt.access-ttl-minutes=15
app.jwt.refresh-ttl-days=7
app.jwt.secret=ctPdN+HDBIkI6N+dYdgOA2x8YC/9aOAUtdoV46VG6Uw=